backend:
  name: github
  repo: designspin/tenacity-interiors

media_folder: static/img
public_folder: /img

collections:
  - name: "config"
    label: "settings"
    delete: false
    files:
      - file: "src/settings/index.md"
        label: "Site Settings"
        name: "settings"
        fields:
          - { label: "Key", name: "key", widget: "hidden", default: "settings"}
          - { label: "Phone Number", name: "phone", widget: "string", default: "01485 521888"}
          - { label: "Company Reg No", name: "regnumber", widget: "string", default: "04914295"}
          - { label: "Vat No", name: "vatnumber", widget: "string", default: "875 7623 77"}
          - label: "Address"
            name: "address"
            widget: "object"
            fields:
              - { label: "Adr1", name: "adr1", widget: "string", default: "Unit 3, Waterford Industrial Estate"}
              - { label: "Adr2", name: "adr2", widget: "string", default: "Mill Lane"}
              - { label: "Adr3", name: "adr3", widget: "string", default: "Great Massingham"}
              - { label: "Town", name: "town", widget: "string", default: "King's Lynn"}
              - { label: "County", name: "county", widget: "string", default: "Norfolk"}
              - { label: "Post Code", name: "postcode", widget: "string", default: "PE32 2HT"}
          - label: "Team"
            name: "team"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: string}
              - { label: "Email", name: "email", widget: string}
          - label: "Social Profiles"
            name: "social"
            widget: "object"
            fields:
              - { label: "Facebook", name: "facebook", widget: "string", default: "https://www.facebook.com/tenacityinteriors"}
              - { label: "Linked In", name: "linkedin", widget: "string", default: "https://www.linkedin.com/in/karl-andrews-a8022159/"}
              - { label: "You Tube", name: "youtube", widget: "string", default: "https://www.youtube.com/channel/UCes99-lSbNJjQgvzcPmdezg"}
  - name: "client-testimonials"
    label: "Client Testimonials"
    folder: "src/pages/client-testimonials"
    create: true
    fields:
      - {label: "Key", name: "key", widget: "hidden", default: "customer-testimonials"}
      - {label: "Quote", name: "quote", widget: "text"}
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Location", name: "location", widget: "string", required: false}
  - name: "interior-designer-testimonials"
    label: "Interior Designer Testimonials"
    folder: "src/pages/interior-designer-testimonials"
    create: true
    fields:
      - {label: "Key", name: "key", widget: "hidden", default: "interior-testimonials"}
      - {label: "Quote", name: "quote", widget: "text"}
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Photo", name: "image", widget: "image", default: "/img/no-photo-large.png"}
  - name: "pages"
    label: "Pages"
    delete: false
    files: 
      - file: "src/pages/kitchens.md"
        label: "Kitchens"
        name: "kitchens"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "page-template"}
          - {label: "Meta Title", name: "metaTitle", widget: "string"}
          - {label: "Meta Description", name: "metaDescription", widget: "string"}
          - {label: "Main Heading", name: "mainHeading", widget: "string"}
          - {label: "Main Text", name: "mainText", widget: "text"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}