backend:
  name: github
  repo: designspin/tenacity-interiors

media_folder: static/img
public_folder: /img

collections:
  - name: "client-testimonials"
    label: "Client Testimonials"
    folder: "src/pages/client-testimonials"
    create: true
    fields:
      - {label: "Key", name: "key", widget: "hidden", default: "testimonials"}
      - {label: "Quote", name: "quote", widget: "text"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Location", name: "location", widget: "string"}
      