backend:
  name: github
  repo: designspin/tenacity-interiors

media_folder: static/img
public_folder: /img

collections:
  - name: "config"
    label: "settings"
    delete: false
    files:
      - file: "src/settings/index.md"
        label: "Site Settings"
        name: "settings"
        fields:
          - { label: "Key", name: "key", widget: "hidden", default: "settings"}
          - { label: "Phone Number", name: "phone", widget: "string", default: "01485 521888"}
          - { label: "Company Reg No", name: "regnumber", widget: "string", default: "04914295"}
          - { label: "Vat No", name: "vatnumber", widget: "string", default: "875 7623 77"}
          - label: "Address"
            name: "address"
            widget: "object"
            fields:
              - { label: "Adr1", name: "adr1", widget: "string", default: "Unit 3, Waterford Industrial Estate"}
              - { label: "Adr2", name: "adr2", widget: "string", default: "Mill Lane"}
              - { label: "Adr3", name: "adr3", widget: "string", default: "Great Massingham"}
              - { label: "Town", name: "town", widget: "string", default: "King's Lynn"}
              - { label: "County", name: "county", widget: "string", default: "Norfolk"}
              - { label: "Post Code", name: "postcode", widget: "string", default: "PE32 2HT"}
          - label: "Team"
            name: "team"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: string}
              - { label: "Email", name: "email", widget: string}
          - label: "Social Profiles"
            name: "social"
            widget: "object"
            fields:
              - { label: "Facebook", name: "facebook", widget: "string", default: "https://www.facebook.com/tenacityinteriors"}
              - { label: "Linked In", name: "linkedin", widget: "string", default: "https://www.linkedin.com/in/karl-andrews-a8022159/"}
              - { label: "You Tube", name: "youtube", widget: "string", default: "https://www.youtube.com/channel/UCes99-lSbNJjQgvzcPmdezg"}
  - name: "client-testimonials"
    label: "Testimonials"
    folder: "src/pages/client-testimonials"
    create: true
    fields:
      - {label: "Key", name: "key", widget: "hidden", default: "customer-testimonials"}
      - {label: "Quote", name: "quote", widget: "text"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Photo", name: "image", widget: "image", default: "/img/no-photo-large.png", required: false}
      - {label: "Location", name: "location", widget: "string", required: false}
      - label: "Type"
        name: "type"
        widget: select
        default: "customer"
        options:
          - {label: "Interior Designer", value: "interior-designer"}
          - {label: "Customer", value: "customer"}
      - label: "Category"
        name: "category"
        widget: "select"
        default: "none"
        options:
          - { label: "Kitchen", value: "handmade-kitchens" }
          - { label: "Bedroom", value: "fitted-bedrooms" }
          - { label: "Vanity Unit", value: "vanity-units" }
          - { label: "Furniture", value: "bespoke-furniture" }
  - name: "interior-designer-testimonials"
    label: "Interior Designer Testimonials"
    folder: "src/pages/interior-designer-testimonials"
    create: true
    fields:
      - {label: "Key", name: "key", widget: "hidden", default: "interior-testimonials"}
      - {label: "Quote", name: "quote", widget: "text"}
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Photo", name: "image", widget: "image", default: "/img/no-photo-large.png"}
  - name: "projects"
    label: "Projects"
    folder: "src/pages/projects"
    create: true
    fields:
      - {label: "Key", name: "key", widget: "hidden", default: "projects"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - label: "Category"
        name: "category"
        widget: "select"
        default: "handmade-kitchens"
        options:
          - { label: "Kitchen", value: "handmade-kitchens" }
          - { label: "Bedroom", value: "fitted-bedrooms" }
          - { label: "Vanity Unit", value: "vanity-units" }
          - { label: "Furniture", value: "bespoke-furniture" }
  - name: "pages"
    label: "Pages"
    delete: false
    files: 
      - file: "src/pages/index.md"
        label: "Home"
        name: "home"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-template"}
          - {label: "Meta Title", name: "metaTitle", widget: "string"}
          - {label: "Meta Description", name: "metaDescription", widget: "string"}
          - {label: "Youtube Video", name: "mainVideo", widget: "string"}
          - {label: "Main Heading", name: "mainHeading", widget: "string"}
          - {label: "Main Text", name: "mainText", widget: "text"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/handmade-kitchens.md"
        label: "Kitchens"
        name: "kitchens"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "page-template"}
          - {label: "Meta Title", name: "metaTitle", widget: "string"}
          - {label: "Meta Description", name: "metaDescription", widget: "string"}
          - {label: "Main Image", name: "mainImage", widget: "image"}
          - {label: "Main Heading", name: "mainHeading", widget: "string"}
          - {label: "Main Text", name: "mainText", widget: "text"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/fitted-bedrooms.md"
        label: "Bedrooms"
        name: "bedrooms"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "page-template"}
          - {label: "Meta Title", name: "metaTitle", widget: "string"}
          - {label: "Meta Description", name: "metaDescription", widget: "string"}
          - {label: "Main Image", name: "mainImage", widget: "image"}
          - {label: "Main Heading", name: "mainHeading", widget: "string"}
          - {label: "Main Text", name: "mainText", widget: "text"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/vanity-units.md"
        label: "Vanity Units"
        name: "vanity-units"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "page-template"}
          - {label: "Meta Title", name: "metaTitle", widget: "string"}
          - {label: "Meta Description", name: "metaDescription", widget: "string"}
          - {label: "Main Image", name: "mainImage", widget: "image"}
          - {label: "Main Heading", name: "mainHeading", widget: "string"}
          - {label: "Main Text", name: "mainText", widget: "text"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/bespoke-furniture.md"
        label: "Bespoke Furniture"
        name: "bespoke-furniture"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "page-template"}
          - {label: "Meta Title", name: "metaTitle", widget: "string"}
          - {label: "Meta Description", name: "metaDescription", widget: "string"}
          - {label: "Main Image", name: "mainImage", widget: "image"}
          - {label: "Main Heading", name: "mainHeading", widget: "string"}
          - {label: "Main Text", name: "mainText", widget: "text"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/interior-designers-architects.md"
        label: "Interior Designers Architects"
        name: "interior-designers-architects"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "default-template"}
          - {label: "Meta Title", name: "metaTitle", widget: "string"}
          - {label: "Meta Description", name: "metaDescription", widget: "string"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/about-us.md"
        label: "About Us"
        name: "about-us"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "default-template"}
          - {label: "Meta Title", name: "metaTitle", widget: "string"}
          - {label: "Meta Description", name: "metaDescription", widget: "string"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/contact.md"
        label: "Contact"
        name: "contact"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact-template"}
          - {label: "Meta Title", name: "metaTitle", widget: "string"}
          - {label: "Meta Description", name: "metaDescription", widget: "string"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/privacy-policy.md"
        label: "Privacy & Cookie Policy"
        name: "privacy"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "privacy-template"}
          - {label: "Meta Title", name: "metaTitle", widget: "string"}
          - {label: "Meta Description", name: "metaDescription", widget: "string"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "About", name: "about", widget: "markdown"}
          - label: "Sections"
            name: "sections"
            widget: list
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Body", name: "body", widget: "markdown"}